on:
  schedule:
   - cron: '*/5 * * * *'

jobs:
  publish_archive_job:
    runs-on: ubuntu-latest
    name: A job to publish Zulip archive in GitHub pages
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run archive
      id: archive
      uses: hackerkid/zulip-archive@actions-followup-1
      with:
        zulip_organization_url: ${{ secrets.zulip_organization_url }}
        zulip_bot_email: ${{ secrets.zulip_bot_email }}
        zulip_bot_key: ${{ secrets.zulip_bot_key }}
        github_personal_access_token: ${{ secrets.github_personal_access_token }}
